#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
# SOURCES := 

SOURCES := ../source/displaydontroller.cpp
SOURCES := ../source/receive_classes.cpp
SOURCES := ../source/send_classes.cpp
SOURCES := ../source/initgame.cpp

# header files in this project
# HEADERS := GameRules.hpp RegGame.hpp keypadclass.hpp 

HEADERS := ../headers/gamerules.hpp
HEADERS := ../headers/reg_game.hpp
HEADERS := ../headers/initgame.hpp
HEADERS := ../headers/keypadclass.hpp

HEADERS := ../headers/time_entity.hpp
HEADERS := ../headers/displayController.hpp

HEADERS := ../headers/receive_classes.hpp
HEADERS := ../headers/send_classes.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory and defer to the Makefile.due
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
