#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../source/displaycontroller.cpp ../source/send_classes.cpp ../source/initgame.cpp

# ../source/receive_classes.cpp

# header files in this project
HEADERS := ../headers/gamerules.hpp ../headers/reg_game.hpp ../headers/initgame.hpp ../headers/keypadclass.hpp ../headers/time_entity.hpp ../headers/displaycontroller.hpp ../headers/send_classes.hpp

#  ../headers/receive_classes.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory and defer to the Makefile.due
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
