#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../source/displaycontroller.cpp ../source/receive_classes.cpp ../source/send_classes.cpp ../source/run_game.cpp ../source/note_player_gpio.cpp ../source/rtttl_player.cpp ../source/initgame.cpp ../source/reg_game.cpp

# header files in this project
HEADERS := ../headers/gamerules.hpp ../headers/reg_game.hpp ../headers/keypadclass.hpp ../headers/displaycontroller.hpp ../headers/receive_classes.hpp ../headers/send_classes.hpp ../headers/run_game.hpp ../headers/button.hpp ../headers/buttonlistener.hpp ../headers/run_game.hpp ../headers/note_player_gpio.hpp ../headers/rtttl_player.hpp ../headers/note.hpp ../headers/beeperCtrl.hpp ../headers/score.hpp ../headers/transferHits.hpp
# ../headers/time_entity.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory and defer to the Makefile.due
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
