#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../../source/receive_classes.cpp ../test_receiver.cpp

# header files in this project
HEADERS :=  ../../headers/receive_classes.hpp ../test_receiver.hpp

# other places to look for files for this project
SEARCH  :=

# set RELATIVE to the next higher directory and defer to the Makefile.due
RELATIVE := $(RELATIVE)../../
include $(RELATIVE)Makefile.due
